### ISSUE TITLE
Database Availibility?

### ISSUE THREAD

**Issue by avinabsaha** [wangjiarui153/AIGCIQA2023#1]
Is the database available to download?

**Comment by wangjiarui153** [comment]
Thank you for your interest on our work. The dataset link is https://www.terabox.com/sharing/link?surl=DtV-A9XiuQQDvVPXn6rYvg

----- 原始邮件 -----
发件人: "Avinab Saha" ***@***.***>
收件人: "wangjiarui153/AIGCIQA2023" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期六, 2023年 7 月 15日 下午 12:28:53
主题: [wangjiarui153/AIGCIQA2023] Database Availibility? (Issue #1)

Is the database available to download?

-- 
Reply to this email directly or view it on GitHub:
https://github.com/wangjiarui153/AIGCIQA2023/issues/1

**Comment by avinabsaha** [comment]
Thanks!

**Comment by avinabsaha** [comment]
Hi @wangjiarui153, could you tell me what attributes Z1, Z2, and Z3 correspond to? I want to know which of Z1,Z2 and Z3 is quality, authenticity, and correspondence respectively. Additionally, where can the text prompts be found?

**Comment by vishaal27** [comment]
@avinabsaha were you able to figure out what the attributes correspond to? Also the text prompts for each image? I am assuming the text prompts could still be figured out using some image-text alignment metric (CLIPScore/ImageReward etc) but not sure if/how we could infer the attributes directly

**Comment by avinabsaha** [comment]
@vishaal27 I am still waiting to hear back from the authors. @wangjiarui153 waiting for your reply! 

I believe the authors should provide the image captions as they were part of the human study.  

The attributes can be figured out by running the NIQE algorithm and computing the performance metrics for each attribute. This is the easiest way, I believe to figure out the attributes.

**Comment by vishaal27** [comment]
Thanks, I can let you know if/when I run a simple test to figure out the text prompts (since we know the source is PartiPrompts). Would you please be able to let me know the attribute mapping if you figure it out? :)

**Comment by avinabsaha** [comment]
@vishaal27 sure! I will let you know! I am planning to work on this early next month!
